### ISSUE TITLE
Error 500 from Daemon when Download, + no GUI

### ISSUE THREAD

**Issue by Meb-Do-Stuff** [FoxRefire/spiceDL#4]
Hey,
After starting the Daemon server, I head to my Spotify, right-click a song -> Download, and nothing appends on the Spotify part.
Heading back to the Daemon console, it reads
```
 * Serving Flask app 'serve'
 * Debug mode: on
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:8888
Press CTRL+C to quit
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 666-054-220
127.0.0.1 - - [10/Feb/2024 12:50:31] "GET /spicedl/start/HAUL%20DOWN%20THE%20HEAVENS/https%3A%2F%2Fopen.spotify.com%2Ftrack%2F5QVuEm1yX7Z5cwHqpbkhKx HTTP/1.1" 500 -
Traceback (most recent call last):
  File "C:\Users\Meb\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2548, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Meb\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Meb\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Meb\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Meb\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Meb\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Meb\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Meb\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Meb\Music\serve.py", line 18, in start
    "proc": subprocess.Popen(['spotdl', url])
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Meb\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Meb\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified
```
I don't know if I've done something wrong, thanks!

**Comment by Meb-Do-Stuff** [comment]
I can't add labels, or am I blind?

**Comment by FoxRefire** [comment]
You have to install [spotDL](https://github.com/spotDL/spotify-downloader) first.
Please installing spotdl and try again.
```
pip install spotdl
```

And what `no GUI` mean?
Probably I guess you want to say there's no downloads list in profile menu. 
If so, this is bug of spicetify side.
In Spicetify v2.31.1, profile menu is not shown because they changed hooking method of profile menu.
Probably this will fixed in next version of spicetify. If you can't wait, use spicetify [v2.31.0](https://github.com/spicetify/spicetify-cli/releases/tag/v2.31.0).

**Comment by Meb-Do-Stuff** [comment]
> You have to install [spotDL](https://github.com/spotDL/spotify-downloader) first. Please installing spotdl and try again.
> 
> ```
> pip install spotdl
> ```

It worked, thanks!

> And what `no GUI` mean? Probably I guess you want to say there's no downloads list in profile menu. If so, this is bug of spicetify side. In Spicetify v2.31.1, profile menu is not shown because they changed hooking method of profile menu. Probably this will fixed in next version of spicetify. If you can't wait, use spicetify [v2.31.0](https://github.com/spicetify/spicetify-cli/releases/tag/v2.31.0).

It works anyway, thanks though!

**Comment by FoxRefire** [comment]
@Meb-Do-Stuff 
Hi, Extension has been updated and the necessary dependencies have been added, so I'll to inform you.
```
pip install tkinter
```
This needs to let users to choose downloading directory.

I also inform you that Spicetify [v2.31.2](https://github.com/spicetify/spicetify-cli/releases/tag/v2.31.2) has been released.
You should update if you are using 2.31.1.
